# This is a basic workflow to help you get started with Actions

name: Build and deploy 

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - '*' # This doesn't mean that it HAS to have a tag, only that the workflow triggers when we push a tag
    branches: [ patch-1-build ]
  pull_request:
    branches: [ patch-1-build ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # On push events only, if it's a "Update X" commit, it's probably something done through the UI - 
    #  so an .md or yaml change, and not something we need to rebuild over
    # We can't simply put !startsWith - see https://github.community/t/expression-syntax-for-not-startswith/17040
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Compile kotlin and build classes
        run: ./gradlew classes
        
      - name: Run code checks
        run: ./gradlew check

      - name: Run unit tests
        run: ./gradlew tests:test


## ANDROID   
     
      - name: Prepare .apk (for Github) files
        continue-on-error: true
        shell: bash
        run: |
          ./gradlew :android:assembleRelease

      - name: Move APK to deploy folder
        continue-on-error: true
        shell: bash
        run: |
          mkdir deploy
          ls android/build/outputs/apk/release
          mv android/build/outputs/apk/release/Unciv-release-unsigned.apk deploy/Unciv-signed.apk

## DESKTOP
      
      - name: Archive Artifacts
        continue-on-error: true
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: deploy
